### ISSUE TITLE
Getting error default value required while refreshing view.

### ISSUE THREAD

**Issue by shantanuharkut** [greenlion/swanhart-tools#111] opened 2015-02-12 12:14 UTC
- I have one field in table with type "date". View  ran successfully first time but while refreshing view I am getting error like default value required.

mysql> desc weekly_data;
+---------------+---------------+------+-----+------------+----------------+
| Field         | Type          | Null | Key | Default    | Extra          |
+---------------+---------------+------+-----+------------+----------------+
| mview$pk      | bigint(20)    | NO   | PRI | NULL       | auto_increment |
| tdate         | date          | YES  |     | NULL |                |
| account_id     | int(11)       | NO   | MUL | NULL       |                |
| visits         | decimal(58,2) | YES  |     | NULL       |                |
| CNT           | bigint(21)    | NO   |     | 0          |                |
+---------------+---------------+------+-----+------------+----------------+

I have other fields which are default NULL, but it only throw error if I use field having type date.

**Comment by greenlion** [comment] 2015-02-12 17:10
After you refresh the view and get error, please run:
SELECT v_sql;

That will show the SQL that Flexviews was trying to execute against the view.

Please also give me the SHOW CREATE TABLE view the view and the view _delta table.

**Comment by shantanuharkut** [comment] 2015-02-12 18:29
mysql> call flexviews.refresh(flexviews.get_id('accounts', 'test_table'),'BOTH',NULL);
ERROR 1364 (HY000): Field 'tdate' doesn't have a default value
mysql> SELECT v_sql;
ERROR 1054 (42S22): Unknown column 'v_sql' in 'field list'

mysql> show create table test_table\G
*************************** 1. row ***************************
       Table: test_table
Create Table: CREATE TABLE `test_table` (
  `mview$pk` bigint(20) NOT NULL AUTO_INCREMENT,
  `tdate` date,
  `client_id` int(11) NOT NULL,
  `client_name` varchar(250) NOT NULL,
  `currency_code` char(10) NOT NULL,
  `vendor` varchar(250) NOT NULL,
  `cost_local` decimal(58,2) DEFAULT NULL,
  `cost_usd` decimal(58,2) DEFAULT NULL,
  `clicks` decimal(58,2) DEFAULT NULL,
  `impressions` decimal(58,2) DEFAULT NULL,
  `sales` decimal(58,2) DEFAULT NULL,
  `CNT` bigint(21) NOT NULL DEFAULT '0',
  PRIMARY KEY (`mview$pk`),
  UNIQUE KEY `client_id` (`client_id`,`client_name`,`currency_code`,`vendor`),
  KEY `key_client_id` (`client_id`),
  KEY `key_client_name` (`client_name`),
  KEY `key_currency_code` (`currency_code`),
  KEY `key_vendor` (`vendor`)
) ENGINE=InnoDB AUTO_INCREMENT=1024 DEFAULT CHARSET=latin1
1 row in set (0.00 sec)


mysql> show create table test_table_delta\G
*************************** 1. row ***************************
       Table: test_table_delta
Create Table: CREATE TABLE `test_table_delta` (
  `dml_type` int(11) DEFAULT NULL,
  `uow_id` bigint(20) DEFAULT NULL,
  `fv$gsn` bigint(20) DEFAULT NULL,
  `tdate` date,
  `client_id` int(11) NOT NULL,
  `client_name` varchar(250) NOT NULL,
  `currency_code` char(10) NOT NULL,
  `vendor` varchar(250) NOT NULL,
  `cost_local` decimal(58,2) DEFAULT NULL,
  `cost_usd` decimal(58,2) DEFAULT NULL,
  `clicks` decimal(58,2) DEFAULT NULL,
  `impressions` decimal(58,2) DEFAULT NULL,
  `sales` decimal(58,2) DEFAULT NULL,
  `CNT` bigint(21) NOT NULL DEFAULT '0',
  KEY `uow_id` (`uow_id`),
  KEY `fv$gsn` (`fv$gsn`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
1 row in set (0.00 sec)

**Comment by greenlion** [comment] 2015-02-12 18:30
select @v_sql;

**Comment by greenlion** [comment] 2015-02-12 18:59
It looks like DATE does not have a DEFAULT NULL or NOT NULL clause.  The  view itself is created by CREATE TABLE ... SELECT followed by INSERT .. SELECT so it is odd that the column doesn't have a NOT NULL or DEFAULT NULL clause.

Can you try the following:
ALTER TABLE test_table modify tdate date NOT NULL;
ALTER TABLE test_table_delta modify tdate date NOT NULL;

**Comment by shantanuharkut** [comment] 2015-02-12 19:03
ran both commands but getting same error again. Also if I set default value to some date then it works

**Comment by greenlion** [comment] 2016-03-17 01:38
I think this is a MySQL bug.  If you have detailed instructions to reproduce (test tables, test data, view create statement) please provide.  closing for now.

**Closed by greenlion** 2016-03-17 01:38 UTC
