### ISSUE TITLE
SQL error from flexcdc.err

### ISSUE THREAD

**Issue by idevin** [greenlion/swanhart-tools#70] opened 2014-04-03 18:39 UTC
SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
SQL_ERROR IN STATEMENT:
SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
SQL_ERROR IN STATEMENT:
SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
SQL_ERROR IN STATEMENT:
SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
SQL_ERROR IN STATEMENT:
SET NAMES utf8 */;

**Comment by huyanping** [comment] 2015-06-02 09:56
I also encountered this error

**Comment by greenlion** [comment] 2015-06-02 15:27
Hi,

Can you provide the binary log that triggered the error?

--Justin

**Comment by huyanping** [comment] 2015-06-02 15:52
Ok, I will find it tomorrow

**Comment by huyanping** [comment] 2015-06-03 06:38
I sent a email to your gmail in the morning

**Comment by wizzvet-cborsenberger** [comment] 2015-09-22 17:01
Hi everybody,

I have the same error :

`SET @@session.max_insert_delayed_threads=0*/;
SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;`

Here my binlog:
/*!40019 SET @@session.max_insert_delayed_threads=0*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;

I think, the problem comes from flexcdc.php:954. The comments are stripped. But in this case, only the first part is stripped : "/*!40019 ".

There are 2 solutions: 
* use a regexp to strip the comment "/* */"
* do not strip the comment at all

But if you strip them, there is surely a good reason :) So why do you strip the comments ?

**Comment by greenlion** [comment] 2015-10-08 02:45
I will take a look at this ASAP.  I can't recall off hand why the comments are stripped.  If I were to guess, it is for the ALTER support, so I may be able to move the stripping to only that portion of code, and/or fix the stripping to resolve this problem.

Do you happen to have a binlog file that exhibits this problem?

**Comment by greenlion** [comment] 2016-03-17 01:41
need binlog to reproduce.

**Comment by greenlion** [comment] 2016-03-24 16:22
Reported in private by user.  Waiting for more info.

**Comment by andy-1bg** [comment] 2016-09-16 16:32
Any word on a fix for this? I am running into the same issue.

`[args] => Array
                (
                    [0] => SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
                    [1] => mysqli Object
                        (
                            [affected_rows] => -1
                            [client_info] => mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $
                            [client_version] => 50012
                            [connect_errno] => 0
                            [connect_error] => 
                            [errno] => 1064
                            [error] => You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '/' at line 1
                            [error_list] => Array
                                (
                                    [0] => Array
                                        (
                                            [errno] => 1064
                                            [sqlstate] => 42000
                                            [error] => You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '/' at line 1
                                        )

                                )

                            [field_count] => 3
                            [host_info] => 127.0.0.1 via TCP/IP
                            [info] => 
                            [insert_id] => 0
                            [server_info] => 5.5.5-10.1.16-MariaDB
                            [server_version] => 50505
                            [stat] => Uptime: 54  Threads: 5  Questions: 86  Slow queries: 0  Opens: 22  Flush tables: 1  Open tables: 14  Queries per second avg: 1.592
                            [sqlstate] => 00000
                            [protocol_version] => 10
                            [thread_id] => 7
                            [warning_count] => 0
                        )

                )`

**Comment by greenlion** [comment] 2016-09-16 19:42
Was it working and stopped, or is this a new setup?

**Comment by andy-1bg** [comment] 2016-09-16 20:13
I believe it was working and then stopped. I deleted the flexviews database and reinstalled and am getting the same error messages now, I can try doing a full whipe of the repository and database.

**Comment by greenlion** [comment] 2016-09-16 22:16
I will see if I can track down the problem.  Are you by chance using an oracle mysqlbinlog against MariaDB?

**Comment by andy-1bg** [comment] 2016-09-16 22:19
I am using the mysqlbinlog from MariaDB 10.1 with a janky bugfix regarding this issue (https://jira.mariadb.org/browse/MDEV-10818).

I essentially hardcoded the version as 10 before the switch case in mysqlbinlog.cc (line 1920) and recompiled.

Thanks for the help!

**Comment by greenlion** [comment] 2016-09-21 01:33
This issue should be fixed with my latest check-in.  Please do a 'git pull' and try again, and let me know if the problem is resolved.  Thanks!

**Comment by andy-1bg** [comment] 2016-09-21 16:08
That did indeed fix it, I appreciate the quick resolution!

**Closed** 2016-09-22 05:18 UTC
